[theme]
primaryColor = "#0095DA"        # Xanh lam của Abbott cho các thành phần chính
backgroundColor = "#F5F6F5"     # Xám trắng nhạt cho nền chính
secondaryBackgroundColor = "#E6ECEF"  # Xám xanh nhạt cho sidebar và các khối phụ
textColor = "#1A2526"           # Đen xám đậm cho văn bản
font = "sans serif"             # Font sans-serif để đồng bộ với phong cách hiện đại của Abbott


[client]
toolbarMode = "minimal"